[package]
name = "ledpwm5947"
version = "0.1.0"
authors = ["Dark Ink <darkink@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.embedded-hal]
version = "0.2.4"
features = ["unproven"]